### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by tbnv** [strangerstudios/pmpro-set-expiration-dates#21]
Hello,

As per the plugin documentation, I'm using `Y2-01-01` for the memberships to expire next year January 1st. However, it's not working because the resulting expiration date is today+1year (e.g. 2020-01-31 as today is 2019-01-31).

Could you fix this asap please? :(

**Comment by eighty20results** [comment]
Hi.

Not sure what you mean since, in my experience, the add-on is working exactly as designed...

Y2 = Next calendar year
Y = Current calendar year.

The correct value for the expiration date, if you want a member checkout sometime after 12/31/2018 to be 12/31/2019, should be: `Y-12-31`. By default, a membership checkout between Jan and Nov 2018 would result in the expiration being set to 12-31-**2018**.

A checkout after 12/01/2018 should generate an expiration date of 12-31-**2019** (see: https://github.com/strangerstudios/pmpro-set-expiration-dates/blob/master/pmpro-set-expiration-dates.php#L107-L111 )

The challenge with the add-on is that it doesn't let the admin select in which month `Y` (2018) should become Y2 (i.e. 2019 - next year) instead.

I.e. if using `Y-12-31` and a user checks out a one year membership level on _11-30-2019_, most of us probably don't want the expiration date to be 12-31-**2019**, but 12-31-**2020** instead (paying for 1 year and getting 1 month is probably going to get us irritated customers).

Most of my customers want the year 'roll-over' for the expiration date to the next year to happen after October 1st, but obviously YMMW.

**Comment by tbnv** [comment]
> I.e. if using Y-12-31 and a user checks out a one year membership level on 11-30-2019, most of us probably don't want the expiration date to be 12-31-2019, but 12-31-2020 instead (paying for 1 year and getting 1 month is probably going to get us irritated customers).

We have a very specific case, people only subscribe in January or February. So I don't the behavior you describe.

The only requirement we have is that a membership must always expire a January 1st (wether it is Y or Y2).

Actually, it's working properly on 1 website that's using PMPro only.

The problem is present on another site that is selling PMPro memberships via WooCommerce. In this case, it looks like the membership expiration is always the one defined in the membership level itself.

**Comment by tbnv** [comment]
I'm also trying to achieve this with a custom function, in a PMPro customization plugin:

```
add_filter('pmpro_checkout_level', 'custom_membership_duration');
function custom_membership_duration($level) {

	// How many years should the membership last?
	$duration = 1;

	// Get dates
	$today = new DateTime();
	$enddate = new DateTime('01-01-'.($today->format('Y') + $duration + 1));

	// Compute and apply the difference
	$difference = $enddate->diff($today);
	$level->expiration_number = $difference->days;
	$level->expiration_period = 'Days';
	
	return $level;
}
```

But it's also not working on this specific website with WooCommerce.

**Comment by messica** [comment]
You should be using the pmprowoo_checkout_level filter for PMPro WooCommerce checkouts:
https://github.com/strangerstudios/pmpro-woocommerce/blob/master/pmpro-woocommerce.php#L200

**Comment by andrewlimaza** [comment]
I am going to mark this ticket as closed, the Set Expiration Date will only work for Paid Memberships Pro checkout and not WooCommerce. 

I'll add this as a feature request to our internal system to keep in mind for future releases.

**Comment by andrewlimaza** [comment]
I do believe this issue has been resolved, if you are still experiencing issues with this please feel free to reach out to our support team on www.paidmembershipspro.com.
