### ISSUE TITLE
Enhancement: Filter to adjust date for renewals

### ISSUE THREAD

**Issue by bwsolutions** [strangerstudios/pmpro-set-expiration-dates#9]
When using set-expiration-dates, you can not renew before the expiration date.  It take the payment, but set the enddate back to original enddate.
For example. if this is set to Y-12-31 to expire at the end of the year.
If you try to renew on 2017-12-15, then it will accept the payment, but put the enddate back to 2017-12-31, rather than setting the date to 2018-12-31.

I think this could easily be fixed by adding a filter to adjust the expiration-date. If you add something like 
```
// call filter to adjust date if needed.
$set_expiration_date = apply_filters('pmprosed_fixdate',$set_expiration_date,$level);
```
to both functions 
`pmprosed_pmpro_level_expiration_text` and `pmprosed_pmpro_checkout_level`
after the calls to 
`$set_expiration_date = pmprosed_fixDate($set_expiration_date);`
This will allow users to adjust the date based on when they want the renewal to be.

As an example, to add a year to the expiration date you could add a filter like

```
function my_pmprosed_fixDate($set_expiration_date,$level = null) {
	// are they renewing?
	if(!empty($level) && pmpro_hasMembershipLevel($level->id)) {
		$timestamp = strtotime($set_expiration_date);
		// add one year
		$set_expiration_date = date("Y-m-d",
				mktime(0, 0, 0,
					date('m', $timestamp),
					date('d', $timestamp),
					date('Y', $timestamp) + 1));
	}
	return $set_expiration_date;
}
add_filter('pmprosed_fixdate', 'my_pmprosed_fixDate', 10,2);
```
Hopefully you can add this to the plugin.
Thanks.

**Comment by aquiferweb** [comment]
I also found this issue recently.
I solved it in the following way (note that this requires modifying the plugin files so changes will be lost if you update the plugin without renaming it or changing version number)

First, modified the pmprosed_fixDate function to allow calculations from timestamps OTHER than the current timestamp (e.g. future expiry dates). (simply added a new variable in the arguments, and used this instead of current_time(‘timestamp’)).

`function tds_pmprosed_fixDate($set_expiration_date,$timestamp_to_work_from)
{
    // handle lower-cased y/m values.
    $set_expiration_date = strtoupper($set_expiration_date);

    //vars to tell us which placeholders are being used
    $has_M = (strpos($set_expiration_date, "M") !== false);
    $has_Y = (strpos($set_expiration_date, "Y") !== false);

    $Y = date("Y", $timestamp_to_work_from);
    $Y2 = intval($Y) + 1;
    $M = date("m", $timestamp_to_work_from);
    if ($M == 12) {
        //set to Jan
        $M2 = "01";

        //set this year to next
        if ($has_Y) {
            $Y = $Y2;
        }
    } else
        $M2 = str_pad(intval($M) + 1, 2, "0", STR_PAD_LEFT);
    $searches = array("Y-", "Y2-", "M-", "M2-");
    $replacements = array($Y . "-", $Y2 . "-", $M . "-", $M2 . "-");

    //note I changed the var name here
    $new_expiration_date = str_replace($searches, $replacements, $set_expiration_date);

    //make sure we don't set expiration dates in the past
    if ($new_expiration_date <= date('Y-m-d', current_time('timestamp'))) {
        if ($has_M) {
            $new_expiration_date = str_replace("M-", "M2-", $set_expiration_date);
        } else {
            $new_expiration_date = str_replace("Y-", "Y2-", $set_expiration_date);  //assume has_Y
        }

        $new_expiration_date = str_replace($searches, $replacements, $new_expiration_date);
    }

    //make sure we use the right day of the month for dates > 28
    $dotm = pmpro_getMatches('/\-([0-3][0-9]$)/', $new_expiration_date, true);
    if (intval($dotm) > 28) {
        $new_expiration_date = date('Y-m-t', strtotime(substr($new_expiration_date, 0, 8) . "01"));
    }

    return $new_expiration_date;
}`

Then, created a new function to check if the user has an expiry date, and return it, or return the current timestamp if not.
`function tds_get_existing_expiry_date($level){
	// are they already expired? 
	global $current_user;
	$user_level = pmpro_getSpecificMembershipLevelForUser( $current_user->ID, $level->id );
	$todays_date = current_time( 'timestamp' );
	$expiration_date = $user_level->enddate;
	$time_left = $expiration_date - $todays_date;
	
	if ( empty( $user_level ) || empty( $user_level->enddate ) || $time_left<=0 ) {
		// user has no future expiration date
		// calculate new date from today's timestamp
		$timestamp_to_work_from = current_time('timestamp');
	}else{
		// user has an expiration date in the future
		// NB  we also add one day to ensure that if we are on the last day of the month, 
		// that we move to the first day of the next month
		// this avoids problem when working with the last day of the month
		
		$timestamp_to_work_from = strtotime("+1 day",$user_level->enddate);
	}

	return $timestamp_to_work_from;
}`

Then, replaced all calls to the prmprosed_fixDate function. 
Replace
`$set_expiration_date = pmprosed_fixDate($set_expiration_date);`
with
`$timestamp_to_work_from = tds_get_existing_expiry_date($level);	
 $set_expiration_date = tds_pmprosed_fixDate($set_expiration_date,$timestamp_to_work_from);`

Note that as I was trying to force all subscriptions to start at the beginning of the month, I had to add an extra day to the ‘timestamp_to_work_from’ to ensure we were definitely in the correct month. I’ve not tested this rigorously for other pmprosed codes, only for the code that we were using Y2-M-01 – so this bit might not be good for general use!

**Comment by jezkerwin** [comment]
Has there been any resolution to this issue?
I am experiencing the same thing.

**Comment by aquiferweb** [comment]
@jezkerwin 
I've been using the solution in my previous comment ever since 2018 - but your comment prompted me to look at updates to this add-on, as I was working on .3 whereas the current add on is at .5.1.
The core code now has the ability to work from a future date rather than the current timestamp (as I proposed above) but as yet, no filters (like @bwsolutions suggests) to allow us to use this ability!

I've adjusted my solution based on bwsolutions sensible idea.

I've modified the core files slightly as follows: in pmpro-set-expiration-dates.php, every time pmprosed_fixDate is called, added a filter afterwards to allow us to adjust the date if necessary (this happens twice as of .5.1).

`        $set_expiration_date = pmprosed_fixDate($set_expiration_date); // old call	
	// new filter call to adjust date if needed.
	$set_expiration_date = apply_filters('pmprosed_fixDate',$set_expiration_date,$level,$discount_code_id);`

Then, in your own functions.php or wherever, add a new function to use this filter. My particular function gets the current expiry date of the user (if present) and re-calculates the new date based on this date instead of the current timestamp.

`function tds_extend_membership($date,$level,$discount_code_id){
	
	global $wpdb;
	
	$current_user = wp_get_current_user();
	
	// is there a current user
	if(!$current_user || $current_user == 0){
		
		// no user, so no need to extend anything
		return $date;
			
	}else{
		
		$user_id = $current_user->ID;															
		
		// get the current enddate of the membership (for current level)
		$user_level = pmpro_getSpecificMembershipLevelForUser( $user_id, $level->id );
		
		$todays_date = current_time( 'timestamp' );
		$expiration_date = $user_level->enddate;
		$time_left = $expiration_date - $todays_date;
		
		if ( empty( $user_level ) || empty( $user_level->enddate ) || $time_left<=0 ) {
			// user has no future expiration date
			// don't change the date
			return $date;
		}else{
			// user has an expiration date in the future
			// use that date when calculating the new expiry		
			$current_expiry_date = $user_level->enddate;
		}
	}
	
	
	// get the code for the set_expiration_date

	//in case the $level object has been cleared out already/etc
	if(empty($level) || empty($level->id))	return $date;
	
	// copied this from the pmpro-set-expiration-dates.php
    if (empty($discount_code_id) && !empty($_REQUEST['discount_code'])) {
        //get discount code passed in
        $discount_code = preg_replace("/[^A-Za-z0-9\-]/", "", $_REQUEST['discount_code']);

        if (!empty($discount_code)) {
            $discount_code_id = $wpdb->get_var("SELECT id FROM $wpdb->pmpro_discount_codes WHERE code = '" . esc_sql($discount_code) . "' LIMIT 1");
        } else {
            $discount_code_id = NULL;
        }
    }
	
    //does this level have a set expiration date?
    $set_expiration_date = pmpro_getSetExpirationDate($level->id, $discount_code_id);
	
	// adjust expiry date based on current expiry date
	if (!empty($set_expiration_date)) {
		$date = pmprosed_fixDate($set_expiration_date,$current_expiry_date);
	}
	
	return $date;
}

add_filter('pmprosed_fixDate','tds_extend_membership',10,3);`

**Comment by andrewlimaza** [comment]
Thanks for the feedback here, I'd most likely suggest in a filter here -> https://github.com/strangerstudios/pmpro-set-expiration-dates/blob/dev/pmpro-set-expiration-dates.php#L151

Or even another filter in the same function before the calculations start, this would allow developers to run some conditional logic to adjust the date on the fly such as if the user already has a membership level set the expiration date text to `Y2-01-01` instead of `Y-12-01` etc.

Around here - https://github.com/strangerstudios/pmpro-set-expiration-dates/blob/dev/pmpro-set-expiration-dates.php#L64

**Comment by andrewlimaza** [comment]
I have added in filters in both places now, it may be 'overkill' but guessing it'll be alright to have both filters.

This will allow you to filter the 'raw' date value before it converts it to an actual date. There will be guides on how to use these filters in the near future.
